# Generated by Django 3.2.5 on 2021-07-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210720_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usd_balance',
            new_name='total_profit_loss',
        ),
    ]
